<a href="https://colab.research.google.com/github/mariodac/Santander-Coders-2024-Data-Science/blob/main/tratando_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tratamento de dados
Foi utilizado o [Dataset](https://drive.google.com/file/d/1rxOZJYfzPAmU1OkgNMjlu78o9y8iVKeS/view?usp=drive_link) com preços de venda e aluguel de casas em São Paulo

In [15]:
import pandas as pd

## Obtendo arquivos do google drive

In [16]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [17]:
df = pd.read_csv('gdrive/MyDrive/Planilhas/Datasets/sao-paulo-properties-april-2019.csv')
df

,Price,Condo,Size,Rooms,Toilets,Suites,Parking,Elevator,Furnished,Swimming Pool,New,District,Negotiation Type,Property Type,Latitude,Longitude
0,930,220,47,2,2,1,1,0,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.543138,-46.479486
1,1000,148,45,2,2,1,1,0,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.550239,-46.480718
2,1000,100,48,2,2,1,1,0,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.542818,-46.485665
3,1000,200,48,2,2,1,1,0,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.547171,-46.483014
4,1300,410,55,2,2,1,1,1,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.525025,-46.482436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13635,265000,420,51,2,1,0,1,0,0,0,0,Jabaquara/São Paulo,sale,apartment,-23.653004,-46.635463
13636,545000,630,74,3,2,1,2,0,0,1,0,Jabaquara/São Paulo,sale,apartment,-23.648930,-46.641982
13637,515000,1100,114,3,3,1,1,0,0,1,0,Jabaquara/São Paulo,sale,apartment,-23.649693,-46.649783
13638,345000,48,39,1,2,1,1,0,1,1,0,Jabaquara/São Paulo,sale,apartment,-23.652060,-46.637046
13639,R$ 161987,0,44,2,1,0,1,0,0,0,0,Jardim Ângela/São Paulo,sale,apartment,-23.613391,-46.523109

## Limpeza de dados

In [18]:
auxiliar = df.loc[13639]
auxiliar

Price                             R$ 161987
Condo                                     0
Size                                     44
Rooms                                     2
Toilets                                   1
Suites                                    0
Parking                                   1
Elevator                                  0
Furnished                                 0
Swimming Pool                             0
New                                       0
District            Jardim Ângela/São Paulo
Negotiation Type                       sale
Property Type                     apartment
Latitude                         -23.613391
Longitude                        -46.523109
Name: 13639, dtype: object

In [19]:
def limpa_preco(linha):
  linha['Price'] = linha['Price'].replace('R$ ', '')
  return linha

In [20]:
limpa_preco(auxiliar)

<ipython-input-19-754a4bea1d74>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  linha['Price'] = linha['Price'].replace('R$ ', '')

Price                                161987
Condo                                     0
Size                                     44
Rooms                                     2
Toilets                                   1
Suites                                    0
Parking                                   1
Elevator                                  0
Furnished                                 0
Swimming Pool                             0
New                                       0
District            Jardim Ângela/São Paulo
Negotiation Type                       sale
Property Type                     apartment
Latitude                         -23.613391
Longitude                        -46.523109
Name: 13639, dtype: object

In [35]:
df = df.apply(lambda x: limpa_preco(x), axis=1)
df

,Price,Condo,Size,Rooms,Toilets,Suites,Parking,Elevator,Furnished,Swimming Pool,New,District,Negotiation Type,Property Type,Latitude,Longitude
0,930,220,47,2,2,1,1,0,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.543138,-46.479486
1,1000,148,45,2,2,1,1,0,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.550239,-46.480718
2,1000,100,48,2,2,1,1,0,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.542818,-46.485665
3,1000,200,48,2,2,1,1,0,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.547171,-46.483014
4,1300,410,55,2,2,1,1,1,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.525025,-46.482436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13635,265000,420,51,2,1,0,1,0,0,0,0,Jabaquara/São Paulo,sale,apartment,-23.653004,-46.635463
13636,545000,630,74,3,2,1,2,0,0,1,0,Jabaquara/São Paulo,sale,apartment,-23.648930,-46.641982
13637,515000,1100,114,3,3,1,1,0,0,1,0,Jabaquara/São Paulo,sale,apartment,-23.649693,-46.649783
13638,345000,48,39,1,2,1,1,0,1,1,0,Jabaquara/São Paulo,sale,apartment,-23.652060,-46.637046
13639,161987,0,44,2,1,0,1,0,0,0,0,Jardim Ângela/São Paulo,sale,apartment,-23.613391,-46.523109

In [32]:
def ajusta_preco(linha):
  linha['Price'] = linha['Price'].replace('.', '')
  preco = int(linha['Price'])
  if(preco < 10000):
    preco = preco * 200
  linha['Price'] = preco
  return linha

In [33]:
auxiliar = df.loc[13639]
auxiliar

Price                                161987
Condo                                     0
Size                                     44
Rooms                                     2
Toilets                                   1
Suites                                    0
Parking                                   1
Elevator                                  0
Furnished                                 0
Swimming Pool                             0
New                                       0
District            Jardim Ângela/São Paulo
Negotiation Type                       sale
Property Type                     apartment
Latitude                         -23.613391
Longitude                        -46.523109
Name: 13639, dtype: object

In [34]:
ajusta_preco(auxiliar)

<ipython-input-32-60e2dbac7c2a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  linha['Price'] = linha['Price'].replace('.', '')
<ipython-input-32-60e2dbac7c2a>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  linha['Price'] = preco

Price                                161987
Condo                                     0
Size                                     44
Rooms                                     2
Toilets                                   1
Suites                                    0
Parking                                   1
Elevator                                  0
Furnished                                 0
Swimming Pool                             0
New                                       0
District            Jardim Ângela/São Paulo
Negotiation Type                       sale
Property Type                     apartment
Latitude                         -23.613391
Longitude                        -46.523109
Name: 13639, dtype: object

In [36]:
df = df.apply(lambda x: ajusta_preco(x), axis=1)
df

,Price,Condo,Size,Rooms,Toilets,Suites,Parking,Elevator,Furnished,Swimming Pool,New,District,Negotiation Type,Property Type,Latitude,Longitude
0,186000,220,47,2,2,1,1,0,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.543138,-46.479486
1,200000,148,45,2,2,1,1,0,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.550239,-46.480718
2,200000,100,48,2,2,1,1,0,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.542818,-46.485665
3,200000,200,48,2,2,1,1,0,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.547171,-46.483014
4,260000,410,55,2,2,1,1,1,0,0,0,Artur Alvim/São Paulo,rent,apartment,-23.525025,-46.482436
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13635,265000,420,51,2,1,0,1,0,0,0,0,Jabaquara/São Paulo,sale,apartment,-23.653004,-46.635463
13636,545000,630,74,3,2,1,2,0,0,1,0,Jabaquara/São Paulo,sale,apartment,-23.648930,-46.641982
13637,515000,1100,114,3,3,1,1,0,0,1,0,Jabaquara/São Paulo,sale,apartment,-23.649693,-46.649783
13638,345000,48,39,1,2,1,1,0,1,1,0,Jabaquara/São Paulo,sale,apartment,-23.652060,-46.637046
13639,161987,0,44,2,1,0,1,0,0,0,0,Jardim Ângela/São Paulo,sale,apartment,-23.613391,-46.523109